Set driver-timeout to 200 seconds due to the exception:
13:44:34.924 [ClusterSystem-akka.actor.default-dispatcher-50] WARN  akka.cluster.ClusterHeartbeatSender - Cluster Node [akka://Cl
usterSystem@172.31.12.158:2552] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [14363] ms ago, expecte
d interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.
g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
13:44:34.926 [ClusterSystem-akka.actor.default-dispatcher-55] WARN  akka.cluster.ClusterHeartbeatSender - Cluster Node [akka://Cl
usterSystem@172.31.12.158:2552] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [19696] ms ago, expecte
d interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.
g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
13:44:34.931 [ClusterSystem-akka.actor.default-dispatcher-49] ERROR akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://Clust
erSystem) - Fatal Aeron error DriverTimeoutException. Have to terminate ActorSystem because it lost contact with the embedded Aer
on media driver. Possible configuration properties to mitigate the problem are 'client-liveness-timeout' or 'driver-timeout'. io.
aeron.exceptions.DriverTimeoutException: MediaDriver keepalive older than (ms): 20000
io.aeron.exceptions.DriverTimeoutException: MediaDriver keepalive older than (ms): 20000